name: Deploy_Lambda

on:
  create:
    tags:
    - v*

jobs:
  deploy_lambda:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: npm install
        env:
          CI: true
        run: |
          npm ci
